[build]
  base = "frontend"
  command = "npm install --legacy-peer-deps && npm run build"

[build.environment]
  NODE_VERSION = "20"

# Essential for Next.js App Router with Clerk
[[plugins]]
  package = "@netlify/plugin-nextjs"
