[build]
  base = "frontend"
  command = "npm install --legacy-peer-deps && npm run build"

[build.environment]
  NODE_VERSION = "20"
  # Clerk Configuration
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY = "pk_test_c3RyaWtpbmctZHJ1bS04Ni5jbGVyay5hY2NvdW50cy5kZXYk"
  CLERK_SECRET_KEY = "sk_test_JsPyjtf63TmLw7wmyNbqW0PxGqMjhDsWeoeh4FzHvW"
  NEXT_PUBLIC_CLERK_SIGN_IN_URL = "/sign-in"
  NEXT_PUBLIC_CLERK_SIGN_UP_URL = "/sign-up"
  NEXT_PUBLIC_CLERK_USER_PROFILE_URL = "/user-profile"
  NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL = "/"
  NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL = "/"
  # Supabase Configuration
  NEXT_PUBLIC_SUPABASE_URL = "https://rehhsubdukbtjhzrbicg.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJlaGhzdWJkdWtidGpoenJiaWNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyODg5NDksImV4cCI6MjA2OTg2NDk0OX0.O-jKbJZvRKb1PWTYpA84JcVYqsNiq8axy7ZFOm6r074"

# Essential for Next.js App Router with Clerk
# The @netlify/plugin-nextjs plugin automatically handles the publish directory
[[plugins]]
  package = "@netlify/plugin-nextjs"
